import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// InvoiceMaker — generated by AppFactoryKit appgen from niche "invoice-maker".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum InvoiceMakerFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "InvoiceMaker",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "dollarsign.circle",
                          title: "InvoiceMaker",
                          message: "Create/send invoices and estimates."),
                    .init(systemImage: "chart.line.uptrend.xyaxis",
                          title: "Go Pro",
                          message: "Unlimited invoices, logo/branding, PDF, tracking.")
                ],
                presentsPaywallOnFinish: true,
                accent: .green
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock InvoiceMaker Pro",
                subheadline: "Unlimited invoices, logo/branding, PDF, tracking.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited invoices"),
                    .init(systemImage: "bolt.fill", title: "Logo/branding"),
                    .init(systemImage: "nosign", title: "PDF"),
                    .init(systemImage: "square.and.arrow.up", title: "Tracking")
                ],
                productIDs: ["invoice-maker_yearly", "invoice-maker_weekly"],
                highlightedProductID: "invoice-maker_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .green, heroSystemImage: "dollarsign.circle")
            )
        )
        return AppFactory(config)
    }
}

@main
struct InvoiceMakerApp: App {
    @StateObject private var factory = InvoiceMakerFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.green)
        }
    }
}
